# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-phatnguyen'
    organization: 'sonarcloud-phatnguyen'
    scannerMode: 'MSBuild'
    projectKey: 'ABCStore'
    extraProperties: |
      sonar.exclusions=**/lib/**
      
- script: cd StoreApp && dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  # workingDirectory: ./StoreApp.App

      
- task: DotNetCoreCLI@2
  displayName: project 1 Test
  continueOnError: true
  inputs:
    command: 'test'
    projects: './StoreApp.Testing'
    arguments: '-c $(buildConfiguration) --collect "XPlat Code Coverage"'


- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud Analysis


- task: SonarCloudPublish@1
  displayName: Publish SonarCloud Analysis
